[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sarawater"
version = "3.1.0"
dependencies = ["numpy", "matplotlib", "pandas", "openpyxl", "scipy"]

[project.optional-dependencies]
dev = ["pytest", "black"]
docs = [
    "sphinx",
    "myst-parser",
    "myst-nb",
    "sphinx-autoapi",
    "sphinxcontrib-bibtex",
    "sphinx-copybutton",
    "sphinx-design",
    "pydata-sphinx-theme"
]

[tool.setuptools]
packages = ["sarawater"]